### ISSUE TITLE
Virtual Ops Meta-Issue

### ISSUE THREAD

**Issue by john-g-g** [steemit/sbds#100]
- [ ] (Not Storing Asset Symbols)[https://github.com/steemit/sbds/issues/97]
- [ ] (Only storing first owner_key, active_key, posting_key, memo_key)[https://github.com/steemit/sbds/issues/96]
- [ ] (Unsupported raw block type )[https://github.com/steemit/sbds/issues/93]
- [ ] ( http server should use aiohttp and jsonrpcserver python packages)[https://github.com/steemit/sbds/issues/92 ]
- [ ] ( fragile syncing behavior, unable to recover from steemd hiccups)[https://github.com/steemit/sbds/issues/90 ]
- [ ] (user vote history call )[https://github.com/steemit/sbds/issues/89]
- [ ] (sbds must also index virtual ops )[https://github.com/steemit/sbds/issues/88 ]
- [ ] (Add methods to sbds to replace account history in steemd )[https://github.com/steemit/sbds/issues/87]
