### ISSUE TITLE
Deploy SBDS to production

### ISSUE THREAD

**Issue by pkattera** [steemit/sbds#113]
## Tasks
- [ ] create postgres db in staging and production
- [ ] update add postgres port and remove mysql port from security groups in staging and production
- [ ] update jussi upstream configs to route sbds traffic 
- [ ] update scalyr config to properly log sbds data

**Comment by pkattera** [comment]
This was previously blocked by https://github.com/steemit/sbds/issues/116 – the blockchain team has resolved that issue, so this issue is unblocked.
